# Generated by Django 2.1.3 on 2018-12-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('parent', models.ManyToManyField(blank=True, related_name='ti_method_parent', to='kvcharts.TiMethod')),
            ],
        ),
    ]
