# Generated by Django 2.1.3 on 2018-12-01 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvcharts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiBenchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_length', models.IntegerField(default=0)),
                ('value_length', models.IntegerField(default=0)),
                ('avg', models.FloatField(default=0.0)),
                ('min', models.FloatField(default=0.0)),
                ('max', models.FloatField(default=0.0)),
                ('ts', models.DateTimeField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvcharts.TiMethod')),
            ],
        ),
    ]
