# Generated by Django 2.1.3 on 2018-12-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvcharts', '0002_tibenchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibenchresult',
            name='kvargs',
            field=models.TextField(blank=True),
        ),
    ]
