# Generated by Django 2.1.3 on 2018-12-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvcharts', '0003_tibenchresult_kvargs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tibenchresult',
            old_name='kvargs',
            new_name='args',
        ),
        migrations.AddField(
            model_name='tibenchresult',
            name='estimates',
            field=models.TextField(blank=True),
        ),
    ]
