# Generated by Django 2.1.3 on 2018-12-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvcharts', '0004_auto_20181201_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tibenchresult',
            old_name='avg',
            new_name='lower_bound',
        ),
        migrations.RenameField(
            model_name='tibenchresult',
            old_name='max',
            new_name='mean',
        ),
        migrations.RenameField(
            model_name='tibenchresult',
            old_name='min',
            new_name='upper_bound',
        ),
    ]
