# Generated by Django 2.1.3 on 2018-12-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvcharts', '0005_auto_20181201_0753'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tibenchresult',
            unique_together={('method', 'args', 'ts')},
        ),
    ]
